---
# AWS Configuration
aws_region: us-east-1
aws_profile: eksuser

# EKS Cluster Configuration
eks_cluster_name: cloudmart
eks_node_group_name: standard-workers
eks_node_type: t3.medium
eks_nodes_count: 1

# ECR Configuration
ecr_backend_repo: cloudmart-backend
ecr_frontend_repo: cloudmart-frontend

# Application Configuration
app_bedrock_agent_id: "F5Q2EGJ3CJ"
app_bedrock_agent_alias_id: "MI0JR9ACY9"
app_openai_api_key: "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"
app_openai_assistant_id: "asst_uQkvMvaBsXkmrUNY9EVotD0F"
app_azure_api_key: "3dc2fe270a57413b8f619bf6eefb76d5"
app_azure_endpoint: "https://eastus.api.cognitive.microsoft.com/"

# Application Paths
app_backend_dir: "/home/ec2-user/challenge-day2/backend"
app_frontend_dir: "/home/ec2-user/challenge-day2/frontend"

# Kubernetes Configuration
k8s_service_account_name: cloudmart-pod-execution-role
k8s_role_name: CloudMartPodExecutionRole

# Pod Replicas
backend_replicas: 1
frontend_replicas: 1

# Frontend conection with Backend
backend_service_name: cloudmart-backend
backend_service_port: 5000  # Adjust as needed
