---
- name: Deploy CloudMart Kubernetes Infrastructure
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    # AWS Configuration - try multiple sources for region
    aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default(lookup('env', 'AWS_REGION')) | default('us-east-1') }}"
    
    # ECR Repository Names
    ecr_backend_repo: "cloudmart-backend"
    ecr_frontend_repo: "cloudmart-frontend"
    
    # Application Configuration
    app_backend_dir: "/tmp/cloudmart-backend"
    app_frontend_dir: "/tmp/cloudmart-frontend"
    
    # Backend Environment Variables
    app_bedrock_agent_id: "{{ lookup('env', 'BEDROCK_AGENT_ID') | default('') }}"
    app_bedrock_agent_alias_id: "{{ lookup('env', 'BEDROCK_AGENT_ALIAS_ID') | default('') }}"
    app_openai_api_key: "{{ lookup('env', 'OPENAI_API_KEY') | default('') }}"
    app_openai_assistant_id: "{{ lookup('env', 'OPENAI_ASSISTANT_ID') | default('') }}"

  pre_tasks:
    - name: Check AWS CLI availability
      shell: which aws
      register: aws_cli_check
      changed_when: false
      failed_when: aws_cli_check.rc != 0
      tags: [always]

    - name: Check Docker availability
      shell: which docker
      register: docker_check
      changed_when: false
      failed_when: docker_check.rc != 0
      tags: [always]

    - name: Verify AWS credentials
      shell: aws sts get-caller-identity
      register: aws_creds_check
      changed_when: false
      failed_when: aws_creds_check.rc != 0
      tags: [always]

    - name: Ensure AWS region is set
      fail:
        msg: "AWS region is not set. Please set AWS_DEFAULT_REGION or AWS_REGION environment variable"
      when: aws_region == ''
      tags: [always]

    - name: Display environment info
      debug:
        msg:
          - "AWS Region: {{ aws_region }}"
          - "AWS Account: {{ (aws_creds_check.stdout | from_json).Account | default('Unknown') }}"
          - "Backend Agent ID: {{ 'Set' if app_bedrock_agent_id else 'Not Set' }}"
          - "OpenAI API Key: {{ 'Set' if app_openai_api_key else 'Not Set' }}"
      tags: [always]

  roles:
    - role: ecr_images
      tags: [ecr, images]

  post_tasks:
    - name: Display deployment summary
      debug:
        msg:
          - "=== CloudMart Deployment Complete ==="
          - "Next steps:"
          - "1. Deploy your Kubernetes manifests"
          - "2. Update your K8s deployments to use the new ECR images"
          - "3. Verify your services are running correctly"
      tags: [always]
